"""Config of activities app."""
from django.apps import AppConfig


class ChatConfig(AppConfig):
    """Configuration of activity app (Generated by django)."""

    default_auto_field = 'django.db.models.BigAutoField'
    name = 'chat'
