# Generated by Django 5.1.1 on 2024-10-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='generation',
            new_name='ku_generation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_single',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tel',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pronoun',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
