# This docker file used only for testing the build functionality
FROM python:3.11-slim-buster

WORKDIR /app
COPY ./backend .
RUN pip install -r requirements.txt


EXPOSE 8000
CMD ["python", "manage.py", "runserver", "8000"]