# Generated by Django 5.1 on 2024-10-02 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('detail', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_people', models.IntegerField(blank=True, null=True)),
                ('people', models.IntegerField(default=0)),
            ],
        ),
    ]
