# Generated by Django 5.1.1 on 2024-10-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_people_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='check_in_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='check_in_code',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='attend',
            name='checked_in',
            field=models.BooleanField(default=True),
        ),
    ]
