# Generated by Django 5.1 on 2024-10-30 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activities.activity'),
        ),
    ]
