# Generated by Django 5.1 on 2024-11-06 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_merge_20241101_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 3, 56, 29, 908621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='activity',
            name='end_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 3, 56, 29, 908621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 3, 56, 29, 908621, tzinfo=datetime.timezone.utc)),
        ),
    ]
