# Generated by Django 5.1.1 on 2024-11-05 03:37

from django.db import migrations


def add_current_host_to_be_owner(apps, schema_editor):
    Activity = apps.get_model('activities', 'Activity')
    for activity in Activity.objects.all():
        activity.owner = activity.host()
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_activity_owner'),
    ]

    operations = [
        migrations.RunPython(add_current_host_to_be_owner),
    ]
