# Generated by Django 5.1 on 2024-11-06 04:10

import activities.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_activity_end_date_activity_end_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(default=activities.models.get_end_date),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_registration_date',
            field=models.DateTimeField(default=activities.models.get_end_registration_date),
        ),
    ]
