# Generated by Django 5.1.1 on 2024-11-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_activity_minium_reputation_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='minium_reputation_score',
            new_name='minimum_reputation_score',
        ),
    ]
