# Generated by Django 5.1.1 on 2024-11-14 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_remove_activity_location_activity_on_site_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.location'),
        ),
    ]
