# Generated by Django 5.1.1 on 2024-11-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_rename_location_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='location',
            new_name='locations',
        ),
    ]
