# Generated by Django 5.1.1 on 2024-11-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_check_in_allowed_activity_check_in_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
