# Generated by Django 5.1 on 2024-10-30 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_attachment_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
    ]
