# Generated by Django 5.1 on 2024-11-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_attend_checked_in'),
        ('activities', '0006_alter_attachment_activity'),
    ]

    operations = [
    ]
