# Generated by Django 5.1 on 2024-11-09 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_alter_activity_owner'),
        ('activities', '0010_attend_rep_decrease'),
    ]

    operations = [
    ]
