# Generated by Django 5.1.1 on 2024-11-13 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_activity_is_cancelled_activity_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
        migrations.AddField(
            model_name='activity',
            name='on_site',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
        ),
    ]
