# Generated by Django 5.1.1 on 2024-11-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_remove_location_activity_activity_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Locations',
        ),
    ]
