"""Config of profile app."""
from django.apps import AppConfig


class ProfilesConfig(AppConfig):
    """Configuration of profile app (Generated by django)."""
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'profiles'
