name: Run tests and check coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATABASE_HOST: 127.0.0.1
  DATABASE_PASSWORD: mju7MJU&
  DJANGO_SETTINGS_MODULE: mysite.settings

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:9.0
        env:
          MYSQL_ROOT_PASSWORD: mju7MJU&
          MYSQL_DATABASE: myDB
          
        ports: ['3306:3306']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install pytest pytest-cov pytest-django

      - name: Run Migrations
        run: |
          cd backend
          python manage.py migrate

      - name: Run tests with coverage
        run: |
          cd backend
          pytest --cov --cov-report=xml  # Already use .coveragerc

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./backend/coverage.xml
          flags: unittests
          name: codecov-umbrella
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}