name: Lint with flake8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install flake8 and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install flake8-docstrings
          cd backend
          pip install -r requirements.txt 

      - name: Run flake8
        run: |
          flake8 --config=.flake8  # Apply config from configuration file
