name: Type check with mypy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mypy-type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install mypy and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install -r requirements.txt

      - name: Run mypy
        run: |
          mypy . --config-file mypy.ini  # Apply config from configuration file
